### ISSUE TITLE
Sort is case sensitive

### ISSUE THREAD

**Issue by lar-ang** [jdcalkins/ng2-data-table#21]
This looks good angular 2 data-table.
But sort is case sensitive. It's some serious.
Is there a way to make the sorting order case insensitive?
I think you can fix this on DataTable.ts.

Please check below
(https://github.com/mariuszfoltak/angular2-datatable/commit/5b92bd282b89c00b5822ce3ea773ea88618d22b6)

**Comment by lar-ang** [comment]
Hello, Are you away?

**Comment by jdcalkins** [comment]
I've been busy. I made the changes, but haven't had a chance to fix the
unit tests and merge my changes.

On May 28, 2017 10:57 AM, "lar-ang" <notifications@github.com> wrote:

Hello, Are you away?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jdcalkins/ng2-data-table/issues/21#issuecomment-304529974>,
or mute the thread

**Comment by lar-ang** [comment]
Thanks for your response.
Please let me download your new ng2-data-table fixed correctly as soon as possible.
Other people also want now.
Regards!

**Comment by lar-ang** [comment]
When can I download fixed version of ng2-data-table?

**Comment by jdcalkins** [comment]
I will see if I can finish it today.

On May 31, 2017 11:41 AM, "lar-ang" <notifications@github.com> wrote:

When can I download fixed version of ng2-data-table?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jdcalkins/ng2-data-table/issues/21#issuecomment-305279422>,
or mute the thread

**Comment by jdcalkins** [comment]
version 1.0.1 fixes this issue

**Comment by lar-ang** [comment]
I updated version 1.0.1, and while building it's error.

ERROR in DataTableModule is not an NgModule

I updated my angular-cli to 1.1.0, and it's same.
How can I fix it?
