### ISSUE TITLE
Error Loading table in html

### ISSUE THREAD

**Issue by ARCHAMO** [jdcalkins/ng2-data-table#24]
Good afternoon, I'm trying to apply the example step by step and the project compiles me correctly but at the moment of visualizing in the browser I get the following error message on the console.

![image](https://user-images.githubusercontent.com/12633358/27446028-a99e921c-5741-11e7-8ba1-244d29b69171.png)

**Comment by jdcalkins** [comment]
The package depends on lodash. That dependency may be missing from
package.json. Try installing lodash.

On Jun 22, 2017 11:55 AM, "ARCHAMO" <notifications@github.com> wrote:

Good afternoon, I'm trying to apply the example step by step and the
project compiles me correctly but at the moment of visualizing in the
browser I get the following error message on the console.

[image: image]
<https://user-images.githubusercontent.com/12633358/27446028-a99e921c-5741-11e7-8ba1-244d29b69171.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jdcalkins/ng2-data-table/issues/24>, or mute the thread
